from sqlalchemy.orm import Session

from app.db.database import SessionLocal
from app.db.models import Game

# Portfolio demo metrics, not live storefront data.
SEED_GAMES = [
    {
        "id": 1,
        "name": "Smalland: Survive the Wilds",
        "price": 34.99,
        "rating": 4.2,
        "review_count": 128,
        "release_year": 2024,
        "developer": "Merge Games",
        "publisher": "Maximum Entertainment",
        "tags": ["Survival", "Multiplayer", "Open World", "Crafting"],
        "summary": "A survival crafting title with strong multiplayer fit and clear collection mechanics.",
        "revenue": 41820,
        "ownership": 1360,
    },
    {
        "id": 2,
        "name": "Celeste",
        "price": 19.99,
        "rating": 4.8,
        "review_count": 312,
        "release_year": 2018,
        "developer": "Maddy Makes Games",
        "publisher": "Extremely OK Games",
        "tags": ["Platformer", "Difficult", "Story Rich", "Singleplayer"],
        "summary": "A precision platformer with exceptional review quality and lasting catalog value.",
        "revenue": 62300,
        "ownership": 4260,
    },
    {
        "id": 3,
        "name": "SIGNALIS",
        "price": 19.99,
        "rating": 4.6,
        "review_count": 204,
        "release_year": 2022,
        "developer": "rose-engine",
        "publisher": "Humble Games",
        "tags": ["Survival Horror", "Atmospheric", "Story Rich", "Singleplayer"],
        "summary": "A high-sentiment horror game with strong narrative identity and review consistency.",
        "revenue": 36400,
        "ownership": 2170,
    },
    {
        "id": 4,
        "name": "Riven",
        "price": 34.99,
        "rating": 4.3,
        "review_count": 84,
        "release_year": 2024,
        "developer": "Cyan Worlds",
        "publisher": "Cyan Worlds",
        "tags": ["Puzzle", "Adventure", "Exploration", "Singleplayer"],
        "summary": "A premium puzzle adventure with clear niche appeal and strong discovery potential.",
        "revenue": 29820,
        "ownership": 920,
    },
    {
        "id": 5,
        "name": "Aimlabs",
        "price": 0,
        "rating": 4.1,
        "review_count": 455,
        "release_year": 2023,
        "developer": "State Space Labs",
        "publisher": "State Space Labs",
        "tags": ["FPS", "Shooter", "Multiplayer", "Training"],
        "summary": "A free-to-play aim trainer with broad acquisition value and competitive positioning.",
        "revenue": 12400,
        "ownership": 15400,
    },
    {
        "id": 6,
        "name": "Mind Over Magic",
        "price": 24.99,
        "rating": 4.0,
        "review_count": 76,
        "release_year": 2025,
        "developer": "Sparkypants",
        "publisher": "Klei Publishing",
        "tags": ["Survival", "Management", "Strategy", "Crafting"],
        "summary": "A management sim with survival hooks and a clear strategy audience.",
        "revenue": 16840,
        "ownership": 780,
    },
    {
        "id": 7,
        "name": "EVERSPACE 2",
        "price": 49.99,
        "rating": 4.4,
        "review_count": 143,
        "release_year": 2023,
        "developer": "ROCKFISH Games",
        "publisher": "ROCKFISH Games",
        "tags": ["Shooter", "Space", "RPG", "Exploration"],
        "summary": "A premium space RPG with strong genre alignment and high-value positioning.",
        "revenue": 71200,
        "ownership": 1530,
    },
    {
        "id": 8,
        "name": "ANIMAL WELL",
        "price": 24.99,
        "rating": 4.7,
        "review_count": 229,
        "release_year": 2024,
        "developer": "Billy Basso",
        "publisher": "Bigmode",
        "tags": ["Metroidvania", "Puzzle", "Exploration", "Atmospheric"],
        "summary": "A compact exploration game with unusually strong sentiment and discovery momentum.",
        "revenue": 58200,
        "ownership": 2710,
    },
    {
        "id": 9,
        "name": "Valheim",
        "price": 19.99,
        "rating": 4.7,
        "review_count": 388,
        "release_year": 2021,
        "developer": "Iron Gate Studio",
        "publisher": "Coffee Stain Publishing",
        "tags": ["Survival", "Multiplayer", "Open World", "Crafting"],
        "summary": "A co-op survival sandbox with strong discovery fit for players who want long-form crafting loops.",
        "revenue": 128000,
        "ownership": 6400,
    },
    {
        "id": 10,
        "name": "Deep Rock Galactic",
        "price": 29.99,
        "rating": 4.8,
        "review_count": 512,
        "release_year": 2020,
        "developer": "Ghost Ship Games",
        "publisher": "Coffee Stain Publishing",
        "tags": ["FPS", "Shooter", "Multiplayer", "Co-op"],
        "summary": "A co-op shooter with unusually durable retention signals and clear squad-based appeal.",
        "revenue": 154000,
        "ownership": 7100,
    },
    {
        "id": 11,
        "name": "Project Zomboid",
        "price": 19.99,
        "rating": 4.6,
        "review_count": 276,
        "release_year": 2013,
        "developer": "The Indie Stone",
        "publisher": "The Indie Stone",
        "tags": ["Survival", "Simulation", "Multiplayer", "Open World"],
        "summary": "A systems-heavy survival game with strong multiplayer watchlist potential and long-tail demand.",
        "revenue": 88200,
        "ownership": 3900,
    },
    {
        "id": 12,
        "name": "Core Keeper",
        "price": 19.99,
        "rating": 4.5,
        "review_count": 188,
        "release_year": 2024,
        "developer": "Pugstorm",
        "publisher": "Fireshine Games",
        "tags": ["Survival", "Crafting", "Multiplayer", "Exploration"],
        "summary": "A cozy survival crafting title with strong collection value for exploration-led recommendations.",
        "revenue": 46200,
        "ownership": 2400,
    },
    {
        "id": 13,
        "name": "Subnautica",
        "price": 29.99,
        "rating": 4.8,
        "review_count": 431,
        "release_year": 2018,
        "developer": "Unknown Worlds Entertainment",
        "publisher": "Unknown Worlds Entertainment",
        "tags": ["Survival", "Exploration", "Atmospheric", "Singleplayer"],
        "summary": "A high-sentiment survival exploration game with strong atmospheric positioning.",
        "revenue": 136500,
        "ownership": 5300,
    },
    {
        "id": 14,
        "name": "Outer Wilds",
        "price": 24.99,
        "rating": 4.8,
        "review_count": 355,
        "release_year": 2020,
        "developer": "Mobius Digital",
        "publisher": "Annapurna Interactive",
        "tags": ["Exploration", "Puzzle", "Story Rich", "Space"],
        "summary": "A discovery-driven mystery game with exceptional sentiment and strong recommendation confidence.",
        "revenue": 94500,
        "ownership": 3700,
    },
    {
        "id": 15,
        "name": "Hades",
        "price": 24.99,
        "rating": 4.8,
        "review_count": 620,
        "release_year": 2020,
        "developer": "Supergiant Games",
        "publisher": "Supergiant Games",
        "tags": ["Action", "Roguelike", "Story Rich", "Singleplayer"],
        "summary": "A polished action roguelike with rare crossover strength between story and repeatable combat.",
        "revenue": 142800,
        "ownership": 6100,
    },
    {
        "id": 16,
        "name": "Hollow Knight",
        "price": 14.99,
        "rating": 4.9,
        "review_count": 540,
        "release_year": 2017,
        "developer": "Team Cherry",
        "publisher": "Team Cherry",
        "tags": ["Metroidvania", "Difficult", "Exploration", "Atmospheric"],
        "summary": "A low-price high-sentiment metroidvania with excellent value and evergreen discovery demand.",
        "revenue": 104000,
        "ownership": 7200,
    },
    {
        "id": 17,
        "name": "Slay the Spire",
        "price": 24.99,
        "rating": 4.8,
        "review_count": 487,
        "release_year": 2019,
        "developer": "Mega Crit",
        "publisher": "Mega Crit",
        "tags": ["Strategy", "Roguelike", "Card Battler", "Singleplayer"],
        "summary": "A strategy deckbuilder with deep replay value and strong fit for analytical recommendations.",
        "revenue": 116000,
        "ownership": 5100,
    },
    {
        "id": 18,
        "name": "Balatro",
        "price": 14.99,
        "rating": 4.9,
        "review_count": 390,
        "release_year": 2024,
        "developer": "LocalThunk",
        "publisher": "Playstack",
        "tags": ["Card Battler", "Roguelike", "Strategy", "Singleplayer"],
        "summary": "A compact card roguelike with exceptional price-to-sentiment performance.",
        "revenue": 76400,
        "ownership": 4800,
    },
    {
        "id": 19,
        "name": "Stardew Valley",
        "price": 14.99,
        "rating": 4.9,
        "review_count": 690,
        "release_year": 2016,
        "developer": "ConcernedApe",
        "publisher": "ConcernedApe",
        "tags": ["Farming", "Simulation", "Cozy", "Multiplayer"],
        "summary": "A cozy farming sim with broad audience reach and strong multiplayer-adjacent appeal.",
        "revenue": 162000,
        "ownership": 9100,
    },
    {
        "id": 20,
        "name": "Against the Storm",
        "price": 29.99,
        "rating": 4.7,
        "review_count": 168,
        "release_year": 2023,
        "developer": "Eremite Games",
        "publisher": "Hooded Horse",
        "tags": ["Strategy", "Management", "Survival", "Simulation"],
        "summary": "A settlement strategy game with survival pressure and strong developer-side category signals.",
        "revenue": 68400,
        "ownership": 2300,
    },
    {
        "id": 21,
        "name": "DREDGE",
        "price": 24.99,
        "rating": 4.6,
        "review_count": 246,
        "release_year": 2023,
        "developer": "Black Salt Games",
        "publisher": "Team17",
        "tags": ["Exploration", "Atmospheric", "Fishing", "Adventure"],
        "summary": "An atmospheric adventure with strong hook clarity and approachable premium pricing.",
        "revenue": 59800,
        "ownership": 2600,
    },
    {
        "id": 22,
        "name": "Disco Elysium",
        "price": 39.99,
        "rating": 4.7,
        "review_count": 310,
        "release_year": 2019,
        "developer": "ZA/UM",
        "publisher": "ZA/UM",
        "tags": ["RPG", "Story Rich", "Detective", "Singleplayer"],
        "summary": "A narrative RPG with standout writing signals and strong story-rich recommendation fit.",
        "revenue": 98200,
        "ownership": 3400,
    },
    {
        "id": 23,
        "name": "No Man's Sky",
        "price": 59.99,
        "rating": 4.3,
        "review_count": 590,
        "release_year": 2016,
        "developer": "Hello Games",
        "publisher": "Hello Games",
        "tags": ["Space", "Exploration", "Multiplayer", "Open World"],
        "summary": "A premium exploration sandbox with broad tag coverage and useful developer comparison signals.",
        "revenue": 185000,
        "ownership": 4200,
    },
    {
        "id": 24,
        "name": "Lethal Company",
        "price": 9.99,
        "rating": 4.6,
        "review_count": 420,
        "release_year": 2023,
        "developer": "Zeekerss",
        "publisher": "Zeekerss",
        "tags": ["Survival Horror", "Multiplayer", "Co-op", "Survival"],
        "summary": "A low-price co-op horror title with strong social discovery and shortlist value.",
        "revenue": 72800,
        "ownership": 8300,
    },
]


def seed_games(db: Session) -> None:
    for game_data in SEED_GAMES:
        game = db.get(Game, game_data["id"])
        if game is None:
            db.add(Game(**game_data))
        else:
            for key, value in game_data.items():
                setattr(game, key, value)
    db.commit()


def main() -> None:
    db = SessionLocal()
    try:
        seed_games(db)
        print(f"Seeded {len(SEED_GAMES)} games.")
    finally:
        db.close()


if __name__ == "__main__":
    main()
