DELETE FROM Produces
DELETE FROM Develops
DELETE FROM UserHasGame
DELETE FROM Developer
DBCC CHECKIDENT ('Developer', RESEED, 0);
DELETE FROM Producer
DBCC CHECKIDENT ('Producer', RESEED, 0);
DELETE FROM HasTag
DELETE FROM Game
DBCC CHECKIDENT ('Game', RESEED, 0);
DELETE FROM [User]
DBCC CHECKIDENT ('[User]', RESEED, 0);
DELETE FROM Tag
DBCC CHECKIDENT ('Tag', RESEED, 0);