CREATE TABLE Produces (
	GameID int REFERENCES Game(ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	ProID int REFERENCES Producer(ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	PRIMARY KEY(GameID, ProID)
	)

CREATE TABLE Develops (
	GameID int REFERENCES Game(ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	DevID int REFERENCES Developer(ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	PRIMARY KEY(GameID, DevID)
	)