CREATE TABLE DevUser (
ID int PRIMARY KEY REFERENCES [User](ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
DeveloperID int not null UNIQUE REFERENCES Developer(ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
)