GRANT EXECUTE ON AddGame TO ArcadeIQApp;
GRANT EXECUTE ON AddUser TO ArcadeIQApp;
GRANT EXECUTE ON GetGameID TO ArcadeIQApp;
GRANT EXECUTE ON RegisterGameDeveloper TO ArcadeIQApp;
GRANT EXECUTE ON RegisterGameProducer TO ArcadeIQApp;
GRANT EXECUTE ON RegisterGameToUser TO ArcadeIQApp;
GRANT EXECUTE ON AddTagToGame TO ArcadeIQApp;
GRANT EXECUTE ON GetUserID TO ArcadeIQApp;
GRANT EXECUTE ON GetUserPassHash TO ArcadeIQApp;